### ISSUE TITLE
Github page não criada

### ISSUE THREAD

**Issue by ruimgbarros** [Shatteris/websitedesign1#1]
Olá Hugo,

Estava a ver o teu trabalho de casa e verifiquei que não criaste uma Github page com o teu trabalho. Podes criar?

**Comment by Shatteris** [comment]
Boa tarde professor, desculpe não ter reparado mais cedo. Eu tentei mexer um pouco nas settings mas não acho que estou a conseguir activar a page, pois agora só me surge um erro 404. 
E pelo que tenho encontrado dizem para clonar o repositorio mas não estou bem a conseguir... desculpe mas não memorizei bem os passos necessarios para criar a pagina na aula... 
Desejo-lhe um bom feriado entretanto

**Comment by ruimgbarros** [comment]
Sem problema. Resolvemos esta questão na próxima aula.

Um abraço!
